feat(builder): add buildx support in builder

diff --git a/docker/19.03/Dockerfile b/docker/19.03/Dockerfile
--- a/docker/19.03/Dockerfile
+++ b/docker/19.03/Dockerfile
@@ -18,6 +18,10 @@ RUN apk add --no-cache \
     unzip \
     zip
 
+##############################
+## INSTALLING BUILDX PLUGIN ##
+##############################
+
 RUN apk add --no-cache \
 		ca-certificates \
 # DOCKER_HOST=ssh://... -- https://github.com/docker/cli/pull/1014
@@ -76,6 +80,37 @@ ENV DOCKER_TLS_CERTDIR=/certs
 # also, ensure the directory pre-exists and has wide enough permissions for "dockerd-entrypoint.sh" to create subdirectories, even when run in "rootless" mode
 RUN mkdir /certs /certs/client && chmod 1777 /certs /certs/client
 # (doing both /certs and /certs/client so that if Docker does a "copy-up" into a volume defined on /certs/client, it will "do the right thing" by default in a way that still works for rootless users)
+
+##############################
+## INSTALLING BUILDX PLUGIN ##
+##############################
+
+ENV DOCKER_BUILDX_VERSION 0.4.2
+
+RUN set -eux; \
+	\
+	apkArch="$(apk --print-arch)"; \
+	case "$apkArch" in \
+		'x86_64') \
+			url="https://github.com/docker/buildx/releases/download/v$DOCKER_BUILDX_VERSION/buildx-v$DOCKER_BUILDX_VERSION.linux-amd64"; \
+			;; \
+		'armhf') \
+			url="https://github.com/docker/buildx/releases/download/v$DOCKER_BUILDX_VERSION/buildx-v$DOCKER_BUILDX_VERSION.linux-arm-v6"; \
+			;; \
+		'armv7') \
+			url="https://github.com/docker/buildx/releases/download/v$DOCKER_BUILDX_VERSION/buildx-v$DOCKER_BUILDX_VERSION.linux-arm-v7"; \
+			;; \
+		'aarch64') \
+			url="https://github.com/docker/buildx/releases/download/v$DOCKER_BUILDX_VERSION/buildx-v$DOCKER_BUILDX_VERSION.linux-arm64"; \
+			;; \
+		*) echo >&2 "error: unsupported architecture ($apkArch)"; exit 1 ;; \
+	esac; \
+	\
+  mkdir -p ~/.docker/cli-plugins; \
+	\
+	wget -nv -O ~/.docker/cli-plugins/docker-buildx "$url"; \
+  \
+  chmod a+x ~/.docker/cli-plugins/docker-buildx;
 
 ENTRYPOINT ["docker-entrypoint.sh"]
 CMD ["sh"]
